# Generated by Django 3.0.1 on 2020-01-02 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_from', models.DateTimeField()),
                ('date_time_to', models.DateTimeField()),
                ('winning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantSlotVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(-1, 'No'), (0, 'If need be'), (1, 'Yes')])),
                ('participant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='his_slots_votes', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_votes', to='perfect_slot.DateTimeSlot')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=256)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('approx_duration', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='their_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datetimeslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfect_slot.Event'),
        ),
        migrations.AddField(
            model_name='datetimeslot',
            name='participants',
            field=models.ManyToManyField(through='perfect_slot.ParticipantSlotVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
