# Generated by Django 3.0.1 on 2020-01-02 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0003_auto_20200102_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantslotvote',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_slots_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
