# Generated by Django 3.0.1 on 2020-01-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0004_auto_20200102_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='is_archive',
        ),
        migrations.AddField(
            model_name='event',
            name='is_in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
