# Generated by Django 3.0.1 on 2020-01-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0005_auto_20200116_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimeslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_datetimeslot', to='perfect_slot.Event'),
        ),
        migrations.AlterField(
            model_name='participantslotvote',
            name='vote',
            field=models.SmallIntegerField(choices=[(-2, 'Did not vote'), (1, 'No'), (3, 'If need be'), (2, 'Yes')], default=-2),
        ),
    ]
