# Generated by Django 3.0.1 on 2020-01-29 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0007_auto_20200127_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='geographical_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT (17.02310484650152 51.10123466736081)', srid=4326),
            preserve_default=False,
        ),
    ]
