# Generated by Django 3.0.1 on 2020-02-01 10:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0008_auto_20200129_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meeting_geographical_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
