# Generated by Django 3.0.1 on 2020-02-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0009_auto_20200201_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_comments',
            field=models.TextField(null=True),
        ),
    ]
