# Generated by Django 3.0.1 on 2020-02-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0010_event_location_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approx_duration',
        ),
    ]
