# Generated by Django 3.0.1 on 2020-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfect_slot', '0011_remove_event_approx_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
